#!/bin/bash

# Quick Start Guide for Real-Time Features
# Run this after setting up Supabase

echo "🎯 QUICK START - Real-Time Backend Setup"
echo "========================================"
echo ""
echo "Follow these steps EXACTLY in order:"
echo ""
echo "STEP 1: Create Free Supabase Project"
echo "------"
echo "1. Go to https://supabase.com"
echo "2. Click 'Sign Up' and create account"
echo "3. Click 'New Project'"
echo "   - Project name: veeru-pro-realtime"
echo "   - Password: (create strong password)"
echo "   - Region: Choose closest to you"
echo "4. Wait 3-5 minutes for project to initialize"
echo ""
echo "STEP 2: Get Your Credentials"
echo "------"
echo "1. In Supabase Dashboard, go to Settings → API"
echo "2. Copy these 3 values:"
echo "   a) Project URL (starting with https://)"
echo "   b) Anon Key (long string starting with eyJ)"
echo "   c) Service Role Key (long string)"
echo ""
echo "STEP 3: Configure Your App"
echo "------"
echo "1. Open file: .env.local"
echo "2. Update these lines with YOUR values:"
echo ""
echo "NEXT_PUBLIC_SUPABASE_URL=https://your-project-id.supabase.co"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJ..."
echo "SUPABASE_SERVICE_ROLE_KEY=eyJ..."
echo ""
echo "STEP 4: Setup Database"
echo "------"
echo "1. In Supabase Dashboard:"
echo "   - Click 'SQL Editor' (on left sidebar)"
echo "   - Click 'New Query'"
echo "   - Copy entire SQL from: REALTIME_SETUP.md"
echo "   - Paste into editor and click 'Run'"
echo ""
echo "STEP 5: Enable Real-Time"
echo "------"
echo "1. In Supabase Dashboard:"
echo "   - Click 'Replication' (on left sidebar)"
echo "   - Find tables: courses, lessons, audit_logs"
echo "   - Toggle ON for each table"
echo ""
echo "STEP 6: Install & Test"
echo "------"
echo "1. Run in terminal:"
echo "   bash setup-realtime.sh"
echo ""
echo "2. Then run:"
echo "   npm run dev"
echo ""
echo "3. Open browser:"
echo "   http://localhost:3000/admin/dashboard"
echo ""
echo "4. Test Real-Time:"
echo "   - Open dashboard in TWO browser windows"
echo "   - Edit something in one window"
echo "   - See it update INSTANTLY in other window (no refresh!)"
echo ""
echo "========================================"
echo "✅ Success! Your app now has real-time features!"
echo ""
echo "📚 For detailed info, read:"
echo "   - REALTIME_SETUP.md (complete SQL & architecture)"
echo "   - DEPLOYMENT_COMPLETE.md (testing & deployment)"
echo ""
