"""
Django settings for academy project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

env = environ.Env(
    DEBUG=(bool, False),
)

# Allow env files at repo root.
# (Previously the repo also hosted a Next.js app; that legacy stack is being removed.)
for candidate in (
    BASE_DIR / '.env',
):
    if candidate.exists():
        environ.Env.read_env(candidate)
        break

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', default='')
if not SECRET_KEY:
    # Dev fallback only; production must set DJANGO_SECRET_KEY.
    SECRET_KEY = 'dev-only-insecure-secret-key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=env.bool('DEBUG', default=False))

_raw_allowed_hosts = env('DJANGO_ALLOWED_HOSTS', default=None)
if _raw_allowed_hosts is None:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', 'testserver']
else:
    ALLOWED_HOSTS = [h.strip() for h in _raw_allowed_hosts.split(',') if h.strip()]

# Vercel sets VERCEL_URL (e.g. "my-app.vercel.app") for preview/prod deployments.
# Auto-allow it to reduce DisallowedHost surprises on free-tier previews.
_vercel_url = env('VERCEL_URL', default='').strip()
if _vercel_url and _vercel_url not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_vercel_url)


# Application definition

INSTALLED_APPS = [
    'daphne',  # Must be first for Channels
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_extensions',
    'django_filters',
    'academy_api',
    'academy_audit',
    'academy_web',
    'academy_users',
    'academy_rbac',
    'academy_courses',
    'academy_projects',
    'academy_learning',
    'academy_payments',
]


# Add dev-only apps and middleware only in DEBUG mode
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'academy.middleware.SecurityHeadersMiddleware',
    'academy.middleware.RateLimitMiddleware',
]

if DEBUG:
    INSTALLED_APPS += ['debug_toolbar', 'silk']
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    MIDDLEWARE.append('silk.middleware.SilkyMiddleware')
    INTERNAL_IPS = ['127.0.0.1', 'localhost']

ROOT_URLCONF = 'academy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'academy.wsgi.application'
ASGI_APPLICATION = 'academy.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': env.db(
        'DATABASE_URL',
        default=f"sqlite:///{(BASE_DIR / 'db.sqlite3').as_posix()}",
    )
}

# Helps with managed Postgres (Neon/Render/etc.)
DATABASES['default']['CONN_MAX_AGE'] = env.int('DJANGO_DB_CONN_MAX_AGE', default=60)
DATABASES['default']['CONN_HEALTH_CHECKS'] = env.bool('DJANGO_DB_CONN_HEALTH_CHECKS', default=True)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = env('DJANGO_LANGUAGE_CODE', default='en-us')

# Supported runtime languages for the UI.
# Users can switch language via POST /i18n/setlang/ (cookie-based, no URL prefix changes).
LANGUAGES = [
    ('en', 'English'),
    ('hi', 'Hindi'),
    ('te', 'Telugu'),
]

LOCALE_PATHS = [str(BASE_DIR / 'locale')]

TIME_ZONE = env('DJANGO_TIME_ZONE', default='UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Source static assets live in repo root `static/`.
STATICFILES_DIRS = [str(BASE_DIR / 'static')]

STATIC_ROOT = env('DJANGO_STATIC_ROOT', default=str(BASE_DIR / 'staticfiles'))

# Whitenoise compression + manifest for long-term caching
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_URL = env('DJANGO_MEDIA_URL', default='/media/')
MEDIA_ROOT = env('DJANGO_MEDIA_ROOT', default=str(BASE_DIR / 'media'))

# Optional S3-compatible media storage (Cloudflare R2 / MinIO / Supabase S3)
# This is intentionally opt-in: set DJANGO_USE_S3_MEDIA=true + credentials.
DJANGO_USE_S3_MEDIA = env.bool('DJANGO_USE_S3_MEDIA', default=False)
if DJANGO_USE_S3_MEDIA:
    INSTALLED_APPS += ['storages']

    AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = env('AWS_S3_ENDPOINT_URL')
    AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', default='auto')
    AWS_S3_ADDRESSING_STYLE = env('AWS_S3_ADDRESSING_STYLE', default='path')
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = env.bool('AWS_QUERYSTRING_AUTH', default=False)

    # Use a dedicated storage backend for user uploads
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        'OPTIONS': {
            'bucket_name': AWS_STORAGE_BUCKET_NAME,
            'endpoint_url': AWS_S3_ENDPOINT_URL,
            'region_name': AWS_S3_REGION_NAME,
            'addressing_style': AWS_S3_ADDRESSING_STYLE,
        },
    }

    # Public bucket URL (recommended for serving media)
    MEDIA_URL = env('DJANGO_S3_PUBLIC_MEDIA_URL', default=MEDIA_URL)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Channels / WebSocket real-time layer
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [env('REDIS_URL', default='redis://localhost:6379')],
        },
    },
}

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

AUTH_USER_MODEL = 'academy_users.User'

# Auth UX defaults for template-first UI
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# Email Configuration
EMAIL_BACKEND = env('DJANGO_EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = env('DJANGO_EMAIL_HOST', default='localhost')
EMAIL_PORT = env.int('DJANGO_EMAIL_PORT', default=25)
EMAIL_HOST_USER = env('DJANGO_EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('DJANGO_EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('DJANGO_EMAIL_USE_TLS', default=False)
EMAIL_USE_SSL = env.bool('DJANGO_EMAIL_USE_SSL', default=False)
DEFAULT_FROM_EMAIL = env('DJANGO_DEFAULT_FROM_EMAIL', default='noreply@veeruproacademy.com')
SERVER_EMAIL = env('DJANGO_SERVER_EMAIL', default=DEFAULT_FROM_EMAIL)

# Domain + security
_raw_csrf_trusted = env('DJANGO_CSRF_TRUSTED_ORIGINS', default=None)
if _raw_csrf_trusted is None:
    CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']
else:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _raw_csrf_trusted.split(',') if o.strip()]

if _vercel_url:
    _vercel_origin = f'https://{_vercel_url}'
    if _vercel_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_vercel_origin)

_raw_cors_allowed = env('DJANGO_CORS_ALLOWED_ORIGINS', default=None)
if _raw_cors_allowed is None:
    CORS_ALLOWED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']
else:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _raw_cors_allowed.split(',') if o.strip()]
CORS_ALLOW_CREDENTIALS = env.bool('DJANGO_CORS_ALLOW_CREDENTIALS', default=True)

DJANGO_STRICT_PRODUCTION = env.bool('DJANGO_STRICT_PRODUCTION', default=False)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# When behind a reverse proxy (Vercel/Cloudflare), Django should respect
# X-Forwarded-Host for building absolute URLs.
USE_X_FORWARDED_HOST = env.bool('DJANGO_USE_X_FORWARDED_HOST', default=DJANGO_STRICT_PRODUCTION)
# IMPORTANT: do not force HTTPS by default in local dev.
# In production, set DJANGO_STRICT_PRODUCTION=true and DJANGO_SECURE_SSL_REDIRECT=true.
SECURE_SSL_REDIRECT = env.bool('DJANGO_SECURE_SSL_REDIRECT', default=(DJANGO_STRICT_PRODUCTION and not DEBUG))
SESSION_COOKIE_SECURE = env.bool('DJANGO_SESSION_COOKIE_SECURE', default=(DJANGO_STRICT_PRODUCTION and not DEBUG))
CSRF_COOKIE_SECURE = env.bool('DJANGO_CSRF_COOKIE_SECURE', default=(DJANGO_STRICT_PRODUCTION and not DEBUG))
SESSION_COOKIE_SAMESITE = env('DJANGO_SESSION_COOKIE_SAMESITE', default='Lax')
CSRF_COOKIE_SAMESITE = env('DJANGO_CSRF_COOKIE_SAMESITE', default='Lax')
SECURE_HSTS_SECONDS = env.int('DJANGO_SECURE_HSTS_SECONDS', default=0 if (DEBUG or not DJANGO_STRICT_PRODUCTION) else 60)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', default=(DJANGO_STRICT_PRODUCTION and not DEBUG))
SECURE_HSTS_PRELOAD = env.bool('DJANGO_SECURE_HSTS_PRELOAD', default=False)

SECURE_CONTENT_TYPE_NOSNIFF = env.bool('DJANGO_SECURE_CONTENT_TYPE_NOSNIFF', default=True)
X_FRAME_OPTIONS = env('DJANGO_X_FRAME_OPTIONS', default='DENY')
SECURE_REFERRER_POLICY = env('DJANGO_SECURE_REFERRER_POLICY', default='same-origin')

LOG_LEVEL = env('DJANGO_LOG_LEVEL', default='INFO' if not DEBUG else 'DEBUG')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
}

# Redis Configuration
REDIS_URL = env('REDIS_URL', default='redis://localhost:6379/0')

# Caching configuration with Redis
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
        },
        'KEY_PREFIX': 'academy',
        'TIMEOUT': 300,  # 5 minutes default
    }
}

# Channels Configuration (WebSocket)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
            'capacity': 1500,
            'expiry': 10,
        },
    },
}

# Development fallback: use in-memory channel layer when Redis isn't available
# or when explicitly requested via DJANGO_USE_INMEMORY_CHANNELS. This makes it
# possible to run and test WebSocket consumers locally without a Redis server.
if DEBUG and env.bool('DJANGO_USE_INMEMORY_CHANNELS', default=True):
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }

# Celery Configuration
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default=REDIS_URL)
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default=REDIS_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 4
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000

# Session configuration for better security with Redis
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 1 week
SESSION_SAVE_EVERY_REQUEST = False  # Only save when modified

# Admin site configuration
ADMIN_SITE_HEADER = "Veeru's Pro Academy"
ADMIN_SITE_TITLE = "VPA Admin"
ADMIN_INDEX_TITLE = "Dashboard"

# Browser caching headers for static files (via WhiteNoise)
WHITENOISE_MAX_AGE = 60 * 60 * 24 * 365 if not DEBUG else 0  # 1 year for production

# Sentry Configuration (Error Monitoring)
SENTRY_DSN = env('SENTRY_DSN', default='')
if SENTRY_DSN and not DEBUG:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.redis import RedisIntegration
    
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            RedisIntegration(),
        ],
        traces_sample_rate=0.1,
        send_default_pii=False,
        environment=env('SENTRY_ENVIRONMENT', default='production'),
    )

if DJANGO_STRICT_PRODUCTION and not DEBUG:
    if SECRET_KEY == 'dev-only-insecure-secret-key':
        raise RuntimeError('DJANGO_SECRET_KEY must be set in production')
    if _raw_allowed_hosts is None:
        raise RuntimeError('DJANGO_ALLOWED_HOSTS must be set in production')
    if _raw_csrf_trusted is None:
        raise RuntimeError('DJANGO_CSRF_TRUSTED_ORIGINS must be set in production')

    # If you're running behind TLS in production, HSTS should be enabled.
    if SECURE_SSL_REDIRECT and SECURE_HSTS_SECONDS <= 0:
        raise RuntimeError('DJANGO_SECURE_HSTS_SECONDS must be > 0 when DJANGO_SECURE_SSL_REDIRECT=true')
