# Generated by Django 4.2.27 on 2026-01-14 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy_courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProofSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('COURSE', 'Course'), ('PROJECT', 'Project')], max_length=16)),
                ('amount', models.FloatField(default=0)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('proof_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='academy_courses.course')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='academy_projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_proofs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['product_type', 'status'], name='academy_pay_product_6d7966_idx'), models.Index(fields=['user', 'submitted_at'], name='academy_pay_user_id_2fd6f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('COURSE', 'Course'), ('PROJECT', 'Project')], max_length=16)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('FREE', 'Free')], default='MANUAL', max_length=16)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='academy_courses.course')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_entitlements', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='academy_projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product_type', 'course', 'project')},
            },
        ),
    ]
