# Generated by Django 4.2.27 on 2026-01-19 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy_courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lesson',
            name='academy_cou_course__1d233d_idx',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academy_courses.module'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'slug')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['slug'], name='academy_cou_slug_adef18_idx'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
