# Generated by Django 4.2.27 on 2026-01-14 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128)),
                ('subject_type', models.CharField(blank=True, max_length=64)),
                ('subject_id', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='academy_aud_action_1e4aae_idx'), models.Index(fields=['subject_type', 'subject_id'], name='academy_aud_subject_f255a4_idx'), models.Index(fields=['actor', 'created_at'], name='academy_aud_actor_i_438a98_idx')],
            },
        ),
    ]
